changelog:
  exclude:
    labels:
      - 'rn: Test(build_output_folders)'
      - 'rn: CI(build_output_folders)'
      - 'rn: Test(cvp_configlet_upload)'
      - 'rn: CI(cvp_configlet_upload)'
      - 'rn: Test(dhcp_provisioner)'
      - 'rn: CI(dhcp_provisioner)'
      - 'rn: Test(eos_cli_config_gen)'
      - 'rn: CI(eos_cli_config_gen)'
      - 'rn: Test(eos_config_deploy_cvp)'
      - 'rn: CI(eos_config_deploy_cvp)'
      - 'rn: Test(eos_config_deploy_eapi)'
      - 'rn: CI(eos_config_deploy_eapi)'
      - 'rn: Test(eos_designs)'
      - 'rn: CI(eos_designs)'
      - 'rn: Test(eos_snapshot)'
      - 'rn: CI(eos_snapshot)'
      - 'rn: Test(eos_validate_state)'
      - 'rn: CI(eos_validate_state)'
      - 'rn: Test(plugins)'
      - 'rn: CI(plugins)'
      - 'rn: Test(requirements)'
      - 'rn: CI(requirements)'
      - 'rn: Test(containers)'
      - 'rn: CI(containers)'
      - 'rn: Test(eos_designs|eos_cli_config_gen)'
      - 'rn: CI(eos_designs|eos_cli_config_gen)'
      - 'rn: Test(eos_cli_config_gen|eos_designs)'
      - 'rn: CI(eos_cli_config_gen|eos_designs)'
      - 'rn: Test(pyavd)'
      - 'rn: CI(pyavd)'
      - 'rn: Test'
      - 'rn: CI'
  categories:
    - title: Breaking Changes
      labels:
        - 'rn: Feat(build_output_folders)!'
        - 'rn: Feat(cvp_configlet_upload)!'
        - 'rn: Feat(dhcp_provisioner)!'
        - 'rn: Feat(eos_cli_config_gen)!'
        - 'rn: Feat(eos_config_deploy_cvp)!'
        - 'rn: Feat(eos_config_deploy_eapi)!'
        - 'rn: Feat(eos_designs)!'
        - 'rn: Feat(eos_snapshot)!'
        - 'rn: Feat(eos_validate_state)!'
        - 'rn: Feat(plugins)!'
        - 'rn: Feat(requirements)!'
        - 'rn: Feat(containers)!'
        - 'rn: Feat(eos_designs|eos_cli_config_gen)!'
        - 'rn: Feat(eos_cli_config_gen|eos_designs)!'
        - 'rn: Fix(build_output_folders)!'
        - 'rn: Fix(cvp_configlet_upload)!'
        - 'rn: Fix(dhcp_provisioner)!'
        - 'rn: Fix(eos_cli_config_gen)!'
        - 'rn: Fix(eos_config_deploy_cvp)!'
        - 'rn: Fix(eos_config_deploy_eapi)!'
        - 'rn: Fix(eos_designs)!'
        - 'rn: Fix(eos_snapshot)!'
        - 'rn: Fix(eos_validate_state)!'
        - 'rn: Fix(plugins)!'
        - 'rn: Fix(requirements)!'
        - 'rn: Fix(containers)!'
        - 'rn: Fix(eos_designs|eos_cli_config_gen)!'
        - 'rn: Fix(eos_cli_config_gen|eos_designs)!'
        - 'rn: Cut(build_output_folders)!'
        - 'rn: Cut(cvp_configlet_upload)!'
        - 'rn: Cut(dhcp_provisioner)!'
        - 'rn: Cut(eos_cli_config_gen)!'
        - 'rn: Cut(eos_config_deploy_cvp)!'
        - 'rn: Cut(eos_config_deploy_eapi)!'
        - 'rn: Cut(eos_designs)!'
        - 'rn: Cut(eos_snapshot)!'
        - 'rn: Cut(eos_validate_state)!'
        - 'rn: Cut(plugins)!'
        - 'rn: Cut(requirements)!'
        - 'rn: Cut(containers)!'
        - 'rn: Cut(eos_designs|eos_cli_config_gen)!'
        - 'rn: Cut(eos_cli_config_gen|eos_designs)!'
        - 'rn: Revert(build_output_folders)!'
        - 'rn: Revert(cvp_configlet_upload)!'
        - 'rn: Revert(dhcp_provisioner)!'
        - 'rn: Revert(eos_cli_config_gen)!'
        - 'rn: Revert(eos_config_deploy_cvp)!'
        - 'rn: Revert(eos_config_deploy_eapi)!'
        - 'rn: Revert(eos_designs)!'
        - 'rn: Revert(eos_snapshot)!'
        - 'rn: Revert(eos_validate_state)!'
        - 'rn: Revert(plugins)!'
        - 'rn: Revert(requirements)!'
        - 'rn: Revert(containers)!'
        - 'rn: Revert(eos_designs|eos_cli_config_gen)!'
        - 'rn: Revert(eos_cli_config_gen|eos_designs)!'
        - 'rn: Refactor(build_output_folders)!'
        - 'rn: Refactor(cvp_configlet_upload)!'
        - 'rn: Refactor(dhcp_provisioner)!'
        - 'rn: Refactor(eos_cli_config_gen)!'
        - 'rn: Refactor(eos_config_deploy_cvp)!'
        - 'rn: Refactor(eos_config_deploy_eapi)!'
        - 'rn: Refactor(eos_designs)!'
        - 'rn: Refactor(eos_snapshot)!'
        - 'rn: Refactor(eos_validate_state)!'
        - 'rn: Refactor(plugins)!'
        - 'rn: Refactor(requirements)!'
        - 'rn: Refactor(containers)!'
        - 'rn: Refactor(eos_designs|eos_cli_config_gen)!'
        - 'rn: Refactor(eos_cli_config_gen|eos_designs)!'
        - 'rn: Bump(build_output_folders)!'
        - 'rn: Bump(cvp_configlet_upload)!'
        - 'rn: Bump(dhcp_provisioner)!'
        - 'rn: Bump(eos_cli_config_gen)!'
        - 'rn: Bump(eos_config_deploy_cvp)!'
        - 'rn: Bump(eos_config_deploy_eapi)!'
        - 'rn: Bump(eos_designs)!'
        - 'rn: Bump(eos_snapshot)!'
        - 'rn: Bump(eos_validate_state)!'
        - 'rn: Bump(plugins)!'
        - 'rn: Bump(requirements)!'
        - 'rn: Bump(containers)!'
        - 'rn: Bump(eos_designs|eos_cli_config_gen)!'
        - 'rn: Bump(eos_cli_config_gen|eos_designs)!'
        - 'rn: Feat!'
        - 'rn: Fix!'
        - 'rn: Cut!'
        - 'rn: Revert!'
        - 'rn: Refactor!'
        - 'rn: Bump!'
    - title: Fixed issues in eos_cli_config_gen
      labels:
        - 'rn: Fix(eos_cli_config_gen)'
    - title: Fixed issues in eos_designs
      labels:
        - 'rn: Fix(eos_designs)'
    - title: Fixed issues in both eos_designs and eos_cli_config_gen
      labels:
        - 'rn: Fix(eos_cli_config_gen|eos_designs)'
        - 'rn: Fix(eos_designs|eos_cli_config_gen)'
    - title: Other Fixed issues
      labels:
        - 'rn: Fix(build_output_folders)'
        - 'rn: Fix(cvp_configlet_upload)'
        - 'rn: Fix(dhcp_provisioner)'
        - 'rn: Fix(eos_config_deploy_cvp)'
        - 'rn: Fix(eos_config_deploy_eapi)'
        - 'rn: Fix(eos_snapshot)'
        - 'rn: Fix(eos_validate_state)'
        - 'rn: Fix(plugins)'
        - 'rn: Fix(requirements)'
        - 'rn: Fix(containers)'
        - 'rn: Fix'
    - title: Documentation
      labels:
        - 'rn: Doc(build_output_folders)'
        - 'rn: Doc(cvp_configlet_upload)'
        - 'rn: Doc(dhcp_provisioner)'
        - 'rn: Doc(eos_cli_config_gen)'
        - 'rn: Doc(eos_config_deploy_cvp)'
        - 'rn: Doc(eos_config_deploy_eapi)'
        - 'rn: Doc(eos_designs)'
        - 'rn: Doc(eos_snapshot)'
        - 'rn: Doc(eos_validate_state)'
        - 'rn: Doc(plugins)'
        - 'rn: Doc(requirements)'
        - 'rn: Doc(containers)'
        - 'rn: Doc(eos_designs|eos_cli_config_gen)'
        - 'rn: Doc(eos_cli_config_gen|eos_designs)'
        - 'rn: Doc'
    - title: New features and enhancements in eos_cli_config_gen
      labels:
        - 'rn: Feat(eos_cli_config_gen)'
    - title: New features and enhancements in eos_designs
      labels:
        - 'rn: Feat(eos_designs)'
    - title: New features and enhancement in both eos_designs and eos_cli_config_gen
      labels:
        - 'rn: Feat(eos_cli_config_gen|eos_designs)'
        - 'rn: Feat(eos_designs|eos_cli_config_gen)'
    - title: Other new features and enhancements
      labels:
        - 'rn: Feat(build_output_folders)'
        - 'rn: Feat(cvp_configlet_upload)'
        - 'rn: Feat(dhcp_provisioner)'
        - 'rn: Feat(eos_config_deploy_cvp)'
        - 'rn: Feat(eos_config_deploy_eapi)'
        - 'rn: Feat(eos_snapshot)'
        - 'rn: Feat(eos_validate_state)'
        - 'rn: Feat(plugins)'
        - 'rn: Feat(requirements)'
        - 'rn: Feat(containers)'
        - 'rn: Feat'
    - title: PyAVD Changes
      labels:
        - 'rn: Feat(pyavd)'
        - 'rn: Fix(pyavd)'
        - 'rn: Cut(pyavd)'
        - 'rn: Doc(pyavd)'
        - 'rn: Bump(pyavd)'
        - 'rn: Revert(pyavd)'
        - 'rn: Refactor(pyavd)'
    - title: Other Changes
      labels:
        - '*'
